version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: keepfresh-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: keepfresh-backend
    ports:
      - "0.0.0.0:8000:8000"
    env_file: .env
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_DEV_HOST: ${NEXT_PUBLIC_DEV_HOST:-}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-}
    container_name: keepfresh-frontend
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data:
